package Server;

public enum Endpoint {
    GET_TASK,
    GET_EPIC,
    GET_SUBTASK,
    GET_ALL_TASKS,
    GET_ALL_EPICS,
    GET_ALL_SUBTASKS,
    GET_EPIC_SUBTASKS,
    GET_HISTORY,
    GET_PRIORITIZED,
    POST_TASK,
    UPDATE_TASK,
    POST_EPIC,
    UPDATE_EPIC,
    POST_SUBTASK,
    UPDATE_SUBTASK,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUBTASK,
    DELETE_ALL_TASKS,
    DELETE_ALL_EPICS,
    DELETE_ALL_SUBTASKS,
    UNKNOWN_ENDPOINT
}
